### ISSUE TITLE
Command to rerender in issue

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-webservices#112] opened 2017-09-25 15:46 UTC
Currently command to rerender is limited to PRs. Should we extend this to issues as well? By adding this to issues, we are making it very easy to rerender and this might result in more CI traffic for no good reason.

cc @ocefpaf

**Comment by ocefpaf** [comment] 2017-09-25 15:53
> Currently command to rerender is limited to PRs. Should we extend this to issues as well? By adding this to issues, we are making it very easy to rerender and this might result in more CI traffic for no good reason.

I guess it is CI limitation vs being human friendly. Let's err on the side of stability and not do that right now. Do you agree?

**Comment by isuruf** [comment] 2017-09-27 02:56
I'm not sure anymore. There are cases where we need to rerender for python and r version upgrades.
FYI. this is only rerender. I've enabled `noarch: python`, because it saves CI.

**Comment by ocefpaf** [comment] 2017-09-27 11:57
If you want to implement that and see how it'll behave I am fine with that. We can always pull the service later.

**Comment by pkgw** [comment] 2018-09-24 14:32
[The docs](https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender) imply that this feature is available. If so it behaves a bit unintuitively: you can't trigger a rerender when *creating* an issue, but only when commenting on a preexisting one: [example](https://github.com/conda-forge/python-casacore-feedstock/issues/6).

**Comment by pkgw** [comment] 2018-09-24 14:35
Also, in the example linked above, rerendering locally *does* in fact cause changes to the recipe.

**Comment by jakirkham** [comment] 2018-09-24 18:01
So this should work in a new issue. Here's an [example]( https://github.com/conda-forge/vigra-feedstock/issues/41 ). If it didn't work though, there may be a bug or a transient issue. Would suggest trying again. If it persists, let's move it to a new issue here.

Tracking the issues down is kind of a chore as we can't really share the logs publicly for security reasons. It would be nice to fix that. In any event, if the issue is repeatable, a core member can step and debug this pretty easily.

**Comment by jakirkham** [comment] 2018-09-24 18:01
Closing as this is completed.

**Closed by jakirkham** 2018-09-24 18:01 UTC
