### ISSUE TITLE
NameError: name 'repo_slug' is not defined

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#274] opened 2019-10-11 16:43 UTC
Caught the following error from the Heroku logs. Posting it here.

```python
2019-10-11T16:39:33.587511+00:00 app[web.1]: ERROR:tornado.application:Uncaught exception POST /conda-webservice-update/hook (140.82.115.250)
2019-10-11T16:39:33.587515+00:00 app[web.1]: HTTPServerRequest(protocol='http', host='conda-forge.herokuapp.com', method='POST', uri='/conda-webservice-update/hook', version='HTTP/1.1', remote_ip='140.82.115.250')
2019-10-11T16:39:33.587518+00:00 app[web.1]: Traceback (most recent call last):
2019-10-11T16:39:33.587520+00:00 app[web.1]:   File "/app/.conda/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
2019-10-11T16:39:33.587523+00:00 app[web.1]:     result = method(*self.path_args, **self.path_kwargs)
2019-10-11T16:39:33.587525+00:00 app[web.1]:   File "/app/conda_forge_webservices/webapp.py", line 294, in post
2019-10-11T16:39:33.587528+00:00 app[web.1]:     state = get_combined_status(token, repo_name, sha)
2019-10-11T16:39:33.587530+00:00 app[web.1]:   File "/app/conda_forge_webservices/webapp.py", line 32, in get_combined_status
2019-10-11T16:39:33.587532+00:00 app[web.1]:     repo = gh.get_repo(repo_slug)
2019-10-11T16:39:33.587535+00:00 app[web.1]: NameError: name 'repo_slug' is not defined
2019-10-11T16:39:33.590722+00:00 app[web.1]: ERROR:tornado.access:500 POST /conda-webservice-update/hook (140.82.115.250) 143.24ms
2019-10-11T16:39:33.580145+00:00 heroku[router]: at=info method=POST path="/conda-forge-command/hook" host=conda-forge.herokuapp.com request_id=0d16f224-6281-4b5c-a97d-0f1f8ccdbf3e fwd="140.82.115.251" dyno=web.1 connect=1ms service=1196ms status=200 bytes=163 protocol=http
```

**Comment by isuruf** [comment] 2019-10-11 17:00
Duplicate of #256

**Closed** 2020-02-03 14:27 UTC
