### ISSUE TITLE
check that noarch: python packages do not use any preprocessing selectors

### ISSUE THREAD

**Issue by notestaff** [conda-forge/conda-forge-webservices#144] opened 2017-10-09 06:08 UTC
Per warning under https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#architecture-independent-packages

**Comment by isuruf** [comment] 2017-10-09 15:39
Duplicate of https://github.com/conda-forge/conda-smithy/issues/578

**Closed by isuruf** 2017-10-09 15:39 UTC
